// <auto-generated />
using System;
using InvestmentOrdersProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentOrdersProject.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711230544_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(32,8)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Name = "Apple",
                            Ticker = "AAPL",
                            UnitPrice = 177.97m
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Name = "Alphabet Inc",
                            Ticker = "GOOGL",
                            UnitPrice = 138.21m
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Name = "Microsoft",
                            Ticker = "MSFT",
                            UnitPrice = 329.04m
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 1,
                            Name = "Coca Cola",
                            Ticker = "KO",
                            UnitPrice = 58.3m
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 1,
                            Name = "Walmart",
                            Ticker = "WMT",
                            UnitPrice = 163.42m
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Name = "BONOS ARGENTINA USD 2030 L.A",
                            Ticker = "AL30",
                            UnitPrice = 307.4m
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 2,
                            Name = "Bonos Globales Argentina USD Step Up 2030",
                            Ticker = "GD30",
                            UnitPrice = 336.1m
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Name = "Delta Pesos Clase A",
                            Ticker = "Delta.Pesos",
                            UnitPrice = 0.0181m
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 3,
                            Name = "Fima Premium Clase A",
                            Ticker = "Fima.Premium",
                            UnitPrice = 0.0317m
                        });
                });

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bono"
                        },
                        new
                        {
                            Id = 3,
                            Description = "FCI"
                        });
                });

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.InvestmentOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(32,8)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(32,8)");

                    b.HasKey("OrderId");

                    b.HasIndex("AssetId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("InvestmentOrders", (string)null);
                });

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateId");

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Description = "En proceso"
                        },
                        new
                        {
                            StateId = 2,
                            Description = "Ejecutado"
                        },
                        new
                        {
                            StateId = 3,
                            Description = "Cancelado"
                        });
                });

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.Asset", b =>
                {
                    b.HasOne("InvestmentOrdersProject.Domain.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("InvestmentOrdersProject.Domain.Entities.InvestmentOrder", b =>
                {
                    b.HasOne("InvestmentOrdersProject.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentOrdersProject.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("OrderStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
